### ISSUE TITLE
데이터프레임 통합본을 불러오는 함수 요청

### ISSUE THREAD

**Issue by chaeha617** [Pray2U/koSlang#1]
데이터 프레임을 생성하는 함수가 현재 ko_data와 slang_TxtToDf 함수 두 가지 인데, 이 두 가지 함수를 통합한 함수가 필요합니다.

**Comment by ash-hun** [comment]
슬랙 확인하시면 해당 함수(작업)의 경우 나중에 병렬로 진행될 예쩡이니 데이터 프레임을 변수에 담아서 작업 진행하시라고 사전에 말씀드렸습니다.
