### ISSUE TITLE
requirements.txt 에 있는 패키지 설치가 되지 않습니다.

### ISSUE THREAD

**Issue by chaeha617** [Pray2U/koSlang#2]
파이참으로 실행시 requirements에 있는 패키지 설치를 추천하여 설치했는데, 설치 도중 설치 실패되어 패키지를 설치할 수 없습니다.
특정 패키지가 설치되지 않는 것이 아니고 아나콘다와 충돌하여 설치가 안되는 것 같습니다.

에러 메시지는 아래와 같습니다.

PS C:\Users\User\PycharmProjects\koslang> conda activate C:\Users\User\anaconda3\envs\koSlang
PS C:\Users\User\PycharmProjects\koslang> C:\Users\User\anaconda3\Scripts\conda.exe install -p C:/Users/User/anacond
a3/envs/koSlang asttokens==2.1.0 -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - asttokens==2.1.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ash-hun** [comment]
루트경로로 가서 `pip install -r requirements.txt`

**Comment by chaeha617** [comment]
터미널에서 해당 코드를 실행해봤습니다. 하지만 에러메시지가 출력되었습니다.

PS C:\Users\User\PycharmProjects\koslang> pip install -r requirements.txt
Processing c:\home\ktietz\src\ci\backcall_1611930011877\work
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\home\\ktietz\\src\\ci
\\backcall_1611930011877\\work'

**Comment by ash-hun** [comment]
pip install -r requirements.txt --user

**Comment by ash-hun** [comment]
https://uwgdqo.tistory.com/361
기존에 설치된 java를 제거하고 해당 링크 참고하여 lts버전의 jdk를 설치한 후 다시 돌려보면 됩니다.
requirements.txt를 실행하지 말고 module.py를 실행하세요.

**Comment by ash-hun** [comment]
#4 를 따로 공지해놓았으니 참고부탁드립니다 :)

**Comment by ash-hun** [comment]
#4 과 이어지는 issue입니다. 해결되었습니다.
