### ISSUE TITLE
slang_processing.py 텍스트 파일 경로 호환 문제 관련

### ISSUE THREAD

**Issue by chaeha617** [Pray2U/koSlang#3]
slang_processing.py의 ko_data() 함수와 slang_TxtToDf()함수에서 사용하는 텍스트 파일의 경로가 slang_processing.py에서의 경로로 지정되어있어 해당 파일을 import하여 두 함수 실행 시 파일경로가 바뀌어 텍스트파일을 읽어올 수 없는 현상 발생

**Comment by chaeha617** [comment]
따라서 해당 두 함수에 path라는 매개변수를 생성하여 함수를 불러오는 위치에서의 텍스트 파일 경로로 불러오는 방식으로 수정

**Comment by ash-hun** [comment]
넵 알겠습니다
