### ISSUE TITLE
각 개발환경 세팅 및 패키지 의존성 설치에 대한 공지

### ISSUE THREAD

**Issue by ash-hun** [Pray2U/koSlang#4]
# koSlang Project 
- ### 개발환경 세팅
    - 기존 `'requirements.txt'`를 삭제하고 `'packagelist.txt'`로 변경해놓았습니다.
    - 패키지 업데이트 및 환경구축 하실 때 아래 명령어를 사용하여 관리하시길 바랍니다.
        - Package Exporting : `conda list --export > packagelist.txt`
        - Package Installing : `conda install --file packagelist.txt`
- ### konlpy 라이브러리 사용문제
    - window 환경에서 `konlpy library`의 `mecab`이 정상적으로 설치가 안됨을 발견하였습니다.
    - 수동설치도 가능하나 빠른 문제해결을 위해 타 라이브러리를 사용하여 진행하도록 하겠습니다.
    - `mecab`의 경우 `eunjeon` 라이브러리를 이용하여 사용하시면 됩니다.
        - 기존 : `from konlpy.tag import Mecab`
        - 현재 : `from eunjeon import Mecab`

환경세팅은 프로젝트의 기본입니다. 패키지와 같이 각기 다른 버전의 도구를 사용하는 경우 별 다른 지시가 없더라도 기본적으로 환경구축은 해보시길 권장합니다 :)

또한, 프로그래밍 이후 commit을 생활화 합시다!

**Comment by chaeha617** [comment]
자바를 재설치 후 konlpy의 함수를 실행 해봤지만 계속 자바 경로가 이전 자바 경로로 맵핑되어 JVM.dll 파일을 사용할 수 없는 것을 확인했습니다.
이에 자바 환경 변수 변경, Jpype 내 자바 경로 변경 등의  조치를 취했지만 이전 자바 경로에서 계속 JVM.dll파일을 불러오려는 시도를 하는 것을 확인했습니다. 
따로 자바 환경 변수를 파이참에서 바꿀 수 있는지 문의 드립니다.

**Comment by ash-hun** [comment]
@chaeha617 개별연락 드린것처럼 긴급미팅 진행하도록 하겠습니다.
12/12 (Mon) 3PM에 방문하도록 할게요.

**Comment by ash-hun** [comment]
JVM 경로재설정 및 해당 문제는 해결되었습니다!
