### ISSUE TITLE
Suggest to use only specific library in our project

### ISSUE THREAD

**Issue by ash-hun** [Pray2U/koSlang#5]
![image](https://user-images.githubusercontent.com/32566767/207342311-003a1653-2f3f-4ea2-935c-410f16abf2e7.png)

보시는것과 같이 `kkma, okt, mecab` 3가지 라이브러리를 이용하여 분별한 문장 구성요소와 그를 구성하는데 걸리는 시간을 비교했을때 아래와 같이 나타납니다.
- Kkma : 약 6.6초
- Okt : 약 2.8초
- Mecab : 약 0.01초

`Mecab` 라이브러리가 독보적으로 우수한 성능을 보이며, 문장 분별결과 또한 아래와 같습니다.
- Kkma : ['안녕', '하', '세요', '?', '저', '의', '이름', '은', '재', '훈', '이', 'ㅂ니다', '.']
- Okt : ['저의 이름', '재훈', '이름'
- Mecab : ['안녕', '하', '세요', '?', '저', '의', '이름', '은', '재훈', '입니다', '.']

제가 판단하기로 문장분별역시 `Mecab` 라이브러리가 가장 정확한 결과를 보인다고 생각합니다. 

따라서, 3가지 라이브러리를 이용하여 각기 다른 문장분석 후 판단하기보단, Mecab 하나의 라이브러리만 사용하여 문장분석을 한 후 진행해도 전체 결과지표에 큰 영향을 줄 수 없다 판단되므로 기존에 사용하던 `Kkma`와 `Okt`를 제거하고 `Mecab` 하나만 사용하고자 합니다. 괜찮을까요?
 @go-ring @chaeha617  보시면 코멘트 달아주세요.

**Comment by chaeha617** [comment]
Kkma와 Okt 라이브러리를 사용하여 만든 문장 분별 값이 Mecab 라이브러리를 사용하여 만든 문장 분별 값에 완벽히 포함되거나, 비속어 필터링 하는데 있어서 문제가 발생하지 않을 정도로 두 값 사이에 미미한 차이만 발생하기 때문에,
저도 Mecab 라이브러리만 사용하는 것이 옳다고 생각합니다~!

**Comment by go-ring** [comment]
네. 제 생각에도 Kkma라이브러리와 Okt 라이브러리를 제거 했을 때, 도출되는 결과물이 현재의 결과와 큰 차이가 발생하지 않을 것 같습니다. 또한 Mecab 라이브러리가 문장을 성분 별로 분류하는 작업과 속도 면에서 가장 우수한 결과를 도출하는 것에 동의하며 Mecab 라이브러리만 사용하는 것에 찬성합니다 !

**Comment by ash-hun** [comment]
넵! 그럼 만장일치로 `mecab` 라이브러리만 사용하는것으로 하겠습니다 :)
